### ISSUE TITLE
Inès Perez - Installing SkyPortal

### ISSUE THREAD

**Issue by Nayru12** [grandma-collaboration/skyportal_grandma_dev#10]
Hi ! :smiley:

I am currently still trying to install SkyPortal and I am stuck as the `make load_demo_data` part, which give me the error : `expected HTTP 200, received 503. Trying again.`
I haven't give up yet and it is a new error, so maybe I will find my answer by myself soon ahah.

Otherwise, I didn't run into noticeable issues while following the beginning of the tutorial : I had a lot of errors at every step, but it was mostly packages that I didn't have on my computer and had to install.

Thank you for your help @Theodlz ! :fire:

**Comment by Theodlz** [comment]
Hi @Nayru12, any updates/progress? Please have a look at other people's issues too (including closed issues, which are not shown by default but you can change that easily) as they might have ran into the same issues as you did.

**Comment by Nayru12** [comment]
Hi @Theodlz, I have tried several more times to get sp to work, but I'm still at the same point, even with the help of others.
As you suggested last time, if it's ok with you, I would like to make a zoom call to help get things work. As I am on vacation, I am available every day of the week at any time.

**Comment by Theodlz** [comment]
Sure thing! What about tomorrow or this weekend during your morning in France? Maybe others need help too. If they do, please coordinate yourself with them so we can have a grouped call.

**Comment by Nayru12** [comment]
Thanks ! For the moment, Manon also wants to participate in the call and I am asking the others to see who is also interested !

**Comment by Nayru12** [comment]
Manon and I are both available this Saturday at 11 am FR time, is it good for you?

**Comment by Theodlz** [comment]
Yes @Nayru12 ! Sorry I didn't confirm here on git only during our meeting 2 days ago.

Is it still ok for you guys?

**Comment by Nayru12** [comment]
Hi @Theodlz, yes it is still ok for us ! :)

**Comment by Theodlz** [comment]
Hi @Nayru12 . Let me know when you make any progress. And also which option you choose in the end: WSL2 or DUAL BOOT (i recommend dual boot which your machine specs)

**Comment by Nayru12** [comment]
Hi @Theodlz. In the end, I choose WSL2.
Right now, I am the `make db_init` command, but suddenly I have encoutered a new issue : my `pip` command does not work anymore, I have the error : `TypeError: deprecated() got an unexpected keyword argument name`

**Comment by mcoughlin** [comment]
https://github.com/aws/aws-cli/issues/7325

Looks like a pyOpenSSL issue.

You could try their suggestion:

pip uninstall pyOpenSSL

or similar? And see if you can get it to build?

**Comment by Nayru12** [comment]
Thank you Michael !
I tried it and it did not work (still the same Error)

**Comment by mcoughlin** [comment]
Hmmm maybe @Theodlz has particular thoughts here. It's definitely a weird one!

**Comment by Theodlz** [comment]
I consistently get that error when my version of pip is inferior to the one required by SkyPortal. Please verify that you are in the virtualenv and yry upgrading pip.
If that doesnt do the trick, delete your virtualenv and create a new one (it should be pretty quick).

If the error persists, please tell me and I'll do some more research in the morning.

**Comment by Nayru12** [comment]
That was the problem. I was in my virtualenv but my pip was not upgraded (and when I upgraded it I was not in my virtualenv...).

So, everything is working now ! I tried to run `make load_demo_data`  and also to change users and it works !
Thank you @Theodlz and Michael ! :) 🥳 

(And for now, my computer seems to support quite well the demo version of sp : it doesn't lag at all with WSL unlike with the VM)
