### ISSUE TITLE
Lydie Pont - Adding New Features 

### ISSUE THREAD

**Issue by lydie10** [grandma-collaboration/skyportal_grandma_dev#13]
Hi @Theodlz ! 👋

I have been following the Adding New Features tutorial, and so far I have read the **Basic React concepts: Elements and Components** and **Redux basics** sections in addition to the [ReactJS](https://reactjs.org/tutorial/tutorial.html) and [Redux](https://redux.js.org/basics/basic-tutorial/) tutorials. 

I'm now reading through the **Adding a new end-to-end SkyPortal feature** section, and I have been wondering : do I have to actually create all the files mentioned in this part ? If so, is it in my own fork ? Or do I have to add them in the skyportal repository clone that was created at the beginning of the [Setup](https://skyportal.io/docs/setup.html) ? 

This question is sort of also related to the tasks that we will have to do next, as I don't know if there is a way to see whether or not our changes are doing the right thing (on the SkyPortal version that we installed), before submitting them in here. 

Thank you for your answer ! 😊

**Comment by lydie10** [comment]
Hi ! Thanks for your explanations, it was very helpful :) 

I'm now trying to implement the new test comment feature. I added the code given in the tutorial but when I launch the app and direct my browser to localhost:5000/test_comments,  I get the following errors when landing on the page :

> Failed to load resource: the server responded with a status of 400 (Bad Request)       api/test_comments:1

> Invalid API endpoint   Notifications.jsx?9cbd:98

Then, when I click on the submit button to add a comment : 

> Failed to load resource: the server responded with a status of 405 (Method Not Allowed)       api/test_comments:1

> HTTP 405: Method Not Allowed

I checked the `skyportal/handlers/api/test_comments.py` file and I didn’t notice any difference from the original code, so I don't know if there is something missing in an other file ?

**Comment by lydie10** [comment]
Hello 😉
I finally completed this tutorial thanks to the new version you posted @Theodlz 
I first started to follow the new documentation in the docs.zip but there was an error with `author_id` in `skyportal/handlers/api/test_comment.py` so I used the code in [doc/adding_features.md](https://github.com/skyportal/skyportal/pull/3662/files) instead.

**Comment by Theodlz** [comment]
Hi @lydie10 , I updated it. The tutorial shouldn't have any errors now. Could you have a look at it and confirm?
