### ISSUE TITLE
Adrien/Adrien Sorting by date saved running out after switching few pages in the SOURCES page

### ISSUE THREAD

**Issue by Adiman007** [grandma-collaboration/skyportal_grandma_dev#15]
If you sort by most recent date saved on page 1 of the sources page, the sorting will be reset after reaching the 3rd page.

**Comment by Theodlz** [comment]
Hi @Adiman007, thanks for opening an issue, great reflex. 
This is a Skyportal issue right? Opening an issue here is great so we can follow your advancements regarding the tasks given to you by Sarah in a centralized manner. However, you also need to create an issue on SkyPortal main (not your fork, the proper SkyPortal). That way, the core team of SP (short for SkyPortal) knows about it and knows that someone is working on it.

**Comment by Theodlz** [comment]
Once any of you have started working on that, please move it to the 'In Progress' column of the project board.

**Comment by Adiman007** [comment]
ok will do !

**Comment by Adiman007** [comment]
hi @Theodlz ,
I have tried working again on it because we worked on the source page during the workshop with Adrien but I can't wrap my head around what's the origin of the problem.
Because I have found a fix to the problem but I just don't know why it does fix the problem :sweat_smile:

**Comment by Theodlz** [comment]
Hi @Adiman007 
A bug fix is still a bug fix hahaha. Open a PR and I'll have a look. As long as we understand why it fixes it its good enough. So lets investigate together

**Comment by Adiman007** [comment]
ok, ok, I just removed a line in SourceTable.jsx and magically the sorting doesn't reset anymore, maybe you will be able to help me understand why, I open the PR asap.

**Comment by Adiman007** [comment]
https://github.com/skyportal/skyportal/pull/3830
P.S : I fixed all the problems in my VScode where 10k files were showned as modified and more :smile:
