### ISSUE TITLE
LIU Céline - Adding new features

### ISSUE THREAD

**Issue by celiune** [grandma-collaboration/skyportal_grandma_dev#16]
Hi @Theodlz :wave: 
I've started the tutorial to [add new features](https://skyportal.io/docs/adding_features.html), but saw that we must first do/read some other tutorials.
So, for now, I'm still working on the [ReactJS Tutorial](https://reactjs.org/tutorial/tutorial.html) and am at the **Function components** section, I'm trying my best to understand it as fast as possible.
Thank you for your time!

**Comment by Theodlz** [comment]
Sounds good to me! 

Don't hesitate to create a little git repo where you commit the code you write when you follow these tutorials. So you can keep it and go back to it as reference later on!

In general, its good practice to always use git when you write code, so to never lose anything. Coding is all about reusing stuff over and over again, so it's very valuable to keep all of what you do.

**Comment by Theodlz** [comment]
Hi @celiune, any updates using the updated tutorial?

**Comment by celiune** [comment]
Hi @Theodlz , I've successfully completed the Adding new features tutorial. I had few errors in your doc.zip, I've removed the "**s**" in the file static/js/ducks/testComments.js lines 13 and 17, I've also changed in the skyportal/handlers/api/test_comment.py file **author_id** by **user_id**.
Before that I've also created a repository with the ReactJS tutorial, the tic tac toe game.
I just have a problem, I can't seem to be able to push my changes in my skyportal repository, I did `git add . ` and `git commit -m "Adding new features"` and it worked well but I can't `git push` 
![image](https://user-images.githubusercontent.com/112829689/201769646-a415a8b7-292b-4d5f-9196-1880056bb7fe.png)

Thank you for your time :rocket:

**Comment by mcoughlin** [comment]
@celiune You should be working on a branch.

i.e.
git checkout -b your_branch
and pushing your changes to that.

**Comment by Theodlz** [comment]
Hey @celiune 
As I explained the other day, you **NEVER** modify your main branch. The main  branch needs to stay the same, so you can simply pull the new changes from skyportal/main on your main. Then, pull the changes from your main to your branches where you are working when needed.

Every time you work on a feature, you create a branch (from MAIN) for that feature.
You can either do it locally with the code Michael gave you above, or create it on github and then checkout to that branch, whatever is easiest for you.

**Comment by celiune** [comment]
Ohh thank you @mcoughlin and @Theodlz , I understand!
