### ISSUE TITLE
Llinares Laura - Adding new features

### ISSUE THREAD

**Issue by laurall974** [grandma-collaboration/skyportal_grandma_dev#18]
Hi ! 😃
I am working on adding new features. I decided to start the task 1 given by Sarah, I had some struggle to find which part of the code I need to modify.
I will give you update **soon**.

Thanks for your help @Theodlz !🚀

**Comment by Theodlz** [comment]
Hi @laurall974, any updates using the updated tutorial?

**Comment by Theodlz** [comment]
Also, this issue you opened is for the Adding New features tutorial, not any task given by Sarah (as you mentioned above). So please do the tutorial first.
