### ISSUE TITLE
Adrien Bonnefoy - Installing SkyPortal

### ISSUE THREAD

**Issue by Adiman007** [grandma-collaboration/skyportal_grandma_dev#2]
@Theodlz  👋 
 #1

I'm at the Launch step in the [Setup](https://skyportal.io/docs/setup.html) and so far everything went great but I'm stuck at the 3rd and 4th step of the Launching process : 

3. Run make log to monitor the service and, in a separate window, make run to start the server.
4. Direct your browser to http://localhost:5000.

the `make run` seems to work without any issue but the `make log` seems to be not working and displays me this error every 30sec :
_[21:20:33 app_1] Could not connect to migration manager on port [64501]
[21:20:33 app_1] Database not migrated, or could not verify; trying again in 2s
[21:20:33 app_2] Could not connect to migration manager on port [64501]
[21:20:33 app_2] Database not migrated, or could not verify; trying again in 2s
[21:20:33 app_3] Could not connect to migration manager on port [64501]
[21:20:33 app_3] Database not migrated, or could not verify; trying again in 2s
[21:20:33 app_0] Could not connect to migration manager on port [64501]
[21:20:33 app_0] Database not migrated, or could not verify; trying again in 2s
[21:20:33 cron] Monitoring 0 jobs
  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml_

When I try to open my browser for the step 4, I arrive on a webpage that displays : 
> SkyPortal is being provisioned
and often it crashes my connection between WSL and VScode when I try to reload the webpage.

I may need help on this because I'm kinda lost and It's very time consuming having to restart my computer if a crash occurs.
❌

**Comment by Theodlz** [comment]
Hi @Adiman007. Any updates ?

**Comment by Theodlz** [comment]
Hi again @Adiman007, anything new?

**Comment by Adiman007** [comment]
sorry I don't have GitHub on my phone so I don't have any alert when you send a text,
but I've watched and have been noticed of what you sent to the others, 
I've made an hard drive partition today and installed Linux into it and now I try it again from the ground 
I hope it will work flawlessly from now on, fingers cross :crossed_fingers:

**Comment by Adiman007** [comment]
Skyporal installed
