### ISSUE TITLE
Manon Flament - Adding new features

### ISSUE THREAD

**Issue by ManonFlt** [grandma-collaboration/skyportal_grandma_dev#21]
Hi @Theodlz 😊
I started the tutorial to add new features. I’ll post my questions here if I have some.
Thank you! 🚀

**Comment by Theodlz** [comment]
Hi @ManonFlt, any updates?

I corrected my new version of the tutorial. I didn't post a new compiled version (no new zip file) but you can have a look at it directly by looking at the MARKDOWN file I edited.

**Comment by ManonFlt** [comment]
Hi @Theodlz 🚀
For now I'm still on the React and Redux tutorials. These are new notions for me so I need a bit more time 😅
