### ISSUE TITLE
Jolyane/Laura/Inès/Alix - Add information from the fink alerts

### ISSUE THREAD

**Issue by jolyanem** [grandma-collaboration/skyportal_grandma_dev#22]
Hi @Theodlz ! 😄 
@laurall974 and I are working on the 5th task given by Sarah which is 'Add information from the fink alerts'. 
We haven't started yet but will focus on it when the tutorial is done. 

Thank you for your time! 🚀

**Comment by Theodlz** [comment]
Hi @jolyanem and @laurall974 

So, this task is a bit different then the rest. It's seperate from SkyPortal, and requires a lot of prior knowledge. However the advancement of this task is pretty critical as it could help a lot with the current GRB/ZTF campaign.
I'll talk with Sarah to figure out if that's really such a good idea to give this task to you guys to start with, as it requires you to understand SkyPortal in depth + other tools, when you just started working on it.

For now focus on the updated tutorial I sent on slack, and contact me again when you are done with that.

**Comment by Theodlz** [comment]
Hi @jolyanem, don't forget to reach out to me when you start working on this. I can definitely help with that and I have a lot of suggestions on how to implement it.
