### ISSUE TITLE
Céline Liu/ Adrien Bonnefoy/ Adrien Bonnefon - Add colors in classification

### ISSUE THREAD

**Issue by celiune** [grandma-collaboration/skyportal_grandma_dev#23]
Hello @Theodlz 👋 
I'll be working on the 2nd task given by Sarah which is `add colors in classification`.
I'll start to work on it when I'll be done with the tutorial.
Thank you for your time! 🚀

**Comment by celiune** [comment]
Hello @Theodlz @mcoughlin ,
With @Adiman007 @KodeurFou we've been working together on this task for weeks, but couldn't give you any update before because we didn't know where and what to search, so we tried to look for where to change the color of the classifications first before knowing that we need to change the background color of the classifications. 
Last week we've gotten [Icare's github's code](https://github.com/grandma-collaboration/icare/blob/main/extensions/skyportal/static/js/components/RecentSources.jsx) and we tried to adapt it on the `ShowClassification.jsx` file. 
However, we've gotten an error that we don't really understand, here are the images of the `make log` as well as the changes we've made on the `ShowClassification.jsx` file as attached documents .
![image](https://user-images.githubusercontent.com/112829689/204926066-cb398b18-b705-46ad-8d9d-b044b80bd62b.png)
![image](https://user-images.githubusercontent.com/112829689/204926107-f46e919d-b256-4c59-a388-a100ed245c45.png)
![image](https://user-images.githubusercontent.com/112829689/204926140-535df502-edf5-4799-b83b-e8c55d1cdbea.png)
![image](https://user-images.githubusercontent.com/112829689/204926465-6e55e7e3-4c0d-4234-a6e1-c4336a1591cb.png)
![image](https://user-images.githubusercontent.com/112829689/204926481-2f40fac1-7060-450e-b80c-4b73284c310f.png)
![image](https://user-images.githubusercontent.com/112829689/204926506-66595819-e31a-4f97-ad62-7ee524f01ea3.png)
Thank you for your time in advance! :rocket:

**Comment by mcoughlin** [comment]
@celiune So we have examples kind of like this in the GcnTags.jsx (which doesn't look all that different from what you are trying). I would have simply copied in the below:

const useStyles = makeStyles(() => ({
  BNS: {
    background: "#468847!important",
  },
  NSBH: {
    background: "#b94a48!important",
  },
  BBH: {
    background: "#333333!important",
  },
  GRB: {
    background: "#f89406!important",
  },
  AMON: {
    background: "#3a87ad!important",
  },
  Terrestrial: {
    background: "#999999!important",
  },
}));

const styles = useStyles();

Changed the names for typical classifications and used the className={styles[tag]} trick in that code. Is that what you were trying?

**Comment by Adiman007** [comment]
Yes that was what we did but we didn't do it well, since it broke the test webpage, we had a white screen or the troubleshooting page when we wanted to access the sources or default page. 
I think it was with the way we manage the application of the styles because the log said that we had an error with a page we didn't change, we will get our head around the problem and we will catch it (finger crossed) .
