### ISSUE TITLE
Carla Amat/Lydie Pont/Manon Flament- Add a legend to the map 

### ISSUE THREAD

**Issue by lydie10** [grandma-collaboration/skyportal_grandma_dev#25]
Hi  @Theodlz ! 👋

I will be working on the 4th task, which is : add a legend to the telescopes map. 
I will start working on it once I'm done with the Adding new features tutorial.

Thanks for your help ! 🚀

**Comment by Theodlz** [comment]
Hi @lydie10. Congrats!! The tutorial has been updated since then, and the error you saw has been removed.
