### ISSUE TITLE
Jolyane/Laura/Inès/Alix - Sort the sources by default by Date Saved (from the most recent)

### ISSUE THREAD

**Issue by Carla802** [grandma-collaboration/skyportal_grandma_dev#26]
Hi @Theodlz ,

This is the first task Sarah gave us, which is sorting the sources by default by Date Saved, from the most to least recent. We decided to all work on this one as a first real practice.

As soon as we finish the Adding features tutorial, each of us will start working on this task.

**Comment by Theodlz** [comment]
Hi @Carla802 

I'm not sure this is a good idea. 10 people is way too much for this.

Most of this task is gonna be looking through the code to figure out what to change, but then its a matter of VERY few lines of code to change/add (like max 10).

I'd rather have you work in groups of 3 to 4 on different tasks at first.
And then 2 to 3 ideally.

**Comment by laurall974** [comment]
Hello @Theodlz, @mcoughlin 
With the team we manage to edit the code and sort the source by default by date saved but I had some struggle trying to push/ commit my code on GitHub from my computer (on VS Code). 
It is written that I have no rights to perform this action. 

I think the error occurred when I cloned my SkyPortal repository but I am not sure at the beginning. 
I don't know how to solve that. 

Thanks for your help ! 🚀

**Comment by Theodlz** [comment]
Hi @laurall974, I answered to @celiune on her issue. Celiune please remember to ask questions on THIS issue instead, which is the one dedicated to this code. Otherwise its a bit confusing to keep track.

Here is my message btw:

```
Hey @celiune
As I explained the other day, you NEVER modify your main branch. The main branch needs to stay the same, so you can simply pull the new changes from skyportal/main on your main. Then, pull the changes from your main to your branches where you are working when needed.

Every time you work on a feature, you create a branch (from MAIN) for that feature.
You can either do it locally with the code Michael gave you above, or create it on github and then checkout to that branch, whatever is easiest for you.
```

**Comment by laurall974** [comment]
@Theodlz I tried to checkout my branch (I had already created one) and to push my code on it but I still have this error : 

`fatal: Authentication failed for 'https://github.com/skyportal/skyportal.git/'`

**Comment by laurall974** [comment]
Thanks @Theodlz it works. 
I pushed the code on the branch `Task1 sort by default by date saved the most recent #3677` and did a pull request.

**Comment by Theodlz** [comment]
I believe this task is finished @jolyanem @laurall974 ! It has been merged on SP. Please close the issue and move it to the right column in the github project.

Good job!!!
