### ISSUE TITLE
Céline Liu/ Adrien Bonnefoy/ Adrien Bonnefon - Add a search bar in "Recent sources"​

### ISSUE THREAD

**Issue by celiune** [grandma-collaboration/skyportal_grandma_dev#28]

**Comment by Theodlz** [comment]
Hi @celiune. I answered @Carla802 regarding this feature, and gave more precise instructions of how to implement it on her PR:
https://github.com/skyportal/skyportal/pull/3671

Please have a look at it

**Comment by celiune** [comment]
Done by @lydie10 @Carla802
