### ISSUE TITLE
Task 2 - unable to see changes

### ISSUE THREAD

**Issue by laurall974** [grandma-collaboration/skyportal_grandma_dev#35]
Hello @Theodlz !
I am trying to do the task 2 given by Sarah. 
I tried to understand the code but I noticed that when I try to make a change on a `.jsx` file, the change does not appear on my Skyportal. (But when I change a `.py` file it appears). 
Maybe I did something wrong during the installation. Have you got any idea of the problem ? 
<img width="807" alt="Screenshot 2022-11-21 at 17 26 55" src="https://user-images.githubusercontent.com/113369147/203108425-309cc267-7a2e-4413-895c-b20eddaae86d.png">

<img width="807" alt="Screenshot 2022-11-21 at 17 27 05" src="https://user-images.githubusercontent.com/113369147/203108437-1bca9786-16c0-4135-bd0e-41aee3301fa5.png">

You can see here I added "test" next to upload photometry (l 252) and it did not change on Skyportal.

Thanks for your help 🚀

**Comment by mcoughlin** [comment]
What happens in make log when you make the change? I usually do a shift refresh in Chrome when developing to be sure the updated web pack is used.

**Comment by Theodlz** [comment]
Hi @laurall974 

If shift refresh doesnt work, here what I do:
Open the menu of your browser that allows you to delete your history. Unselect all options except cache (some browser hide most options and you need to click show all/advanced to see them). Select period all, and hit confirm to delete ONLY the cache of your browser. Then you can refresh the page and you should see your changes.

**Comment by laurall974** [comment]
It works ! Thanks a lot @mcoughlin @Theodlz
