### ISSUE TITLE
Errors in make log

### ISSUE THREAD

**Issue by lydie10** [grandma-collaboration/skyportal_grandma_dev#36]
Hi @Theodlz 
I was trying to make the changes you requested for the legend but now I have an issue when I do `make log`. 

It's happening since I synchronized my local branch. Now it says that everything is up to date in my local branch, but the thing is that I don't have the same files when I look at the branch online as when I do on my local one.  
For example, locally, I have a Main.jsx file that is not supposed to be there and that causes other errors with TestComments.jsx that also does not exist in this branch. 

The issue is that I can't open SkyPortal on localhost:5000 as it shows a blank page, even though I can commit my changes without any conflicts.
I don't know if there is a way to solve this or if I have to create a new clone.

Thanks for your help ! 

[log.zip](https://github.com/grandma-collaboration/skyportal_grandma_dev/files/10059272/log.zip)

![errors make log](https://user-images.githubusercontent.com/115883967/203124334-7f569006-7e55-4555-94dc-2f2fb6e3d2a8.PNG)

**Comment by Theodlz** [comment]
Hi Lydie.

Stop your app, then delete the package-lock.json file and the node_modules directory. Then run the app again to reinstall dependencies. That will fix it

**Comment by lydie10** [comment]
Thanks ! I tried this and it solved one of the errors with node_module in the logs. 
However, some of the messages are still remaining  : 
 
> [21:36:59 service/webpack] ERROR in ./static/js/components/Main.jsx 68:0-42
[21:36:59 service/webpack] Module not found: Error: Can't resolve './TestComments' in '/home/lydie/skyportal-fork/skyportal/static/js/components'
[21:36:59 service/webpack] resolve './TestComments' in '/home/lydie/skyportal-fork/skyportal/static/js/components'
[21:36:59 service/webpack] using description file: /home/lydie/skyportal-fork/skyportal/package.json (relative path: ./static/js/components)
[21:36:59 service/webpack] Field 'browser' doesn't contain a valid alias configuration
[21:36:59 service/webpack] using description file: /home/lydie/skyportal-fork/skyportal/package.json (relative path: ./static/js/components/TestComments)
[21:36:59 service/webpack] no extension
[21:36:59 service/webpack] Field 'browser' doesn't contain a valid alias configuration

**Comment by mcoughlin** [comment]
Looks like you aren't importing TestComments with "./TestComments.jsx" ?

**Comment by Theodlz** [comment]
To me the error you get is still related to which node modules are installed, did you remove the package-lock.json AND the whole node_modules folder for sure? (for the browser part of the error)
However it seems to happen only in your component.
Here's what I think:
In your config.yaml, you still have a reference to the TestComment component, but however you are working on another branch of skyportal that does not have that component.

So please try to deleted your config.yaml, and recreate one based on the default one.

**Comment by lydie10** [comment]
I created a new config.yaml file and now it's working ! 
Next time I'll make sure to be more careful about what's in this file. 
Thank you for your help ! 🙂

**Comment by Theodlz** [comment]
I suggest you create a new one everytime you update skyportal. Anyway in development that shouldn't be a problem
