### ISSUE TITLE
Issue on Skyportal 

### ISSUE THREAD

**Issue by jolyanem** [grandma-collaboration/skyportal_grandma_dev#37]
Hello @Theodlz  ! :smile: sorry to bother you during christmas vacations. I would like to show my errors on SP in order to fix it. 
When I try to `make run` and then `make log` : 
![makerunmakelog](https://user-images.githubusercontent.com/105995521/209426964-a8192e6d-180c-4843-ba7e-88d642611e90.png)

Then I tried : `make db_clear && make db_init && make run`. And here is the `make log` 
![Screenshot_2022-12-24_09_08_56](https://user-images.githubusercontent.com/105995521/209427137-62f20882-18d9-42be-86db-4a7ec203fc5a.png)
So I thought the problem came from my pg_hba.conf but I don't really see how can I change it to make it work. 
![Screenshot_2022-12-24_09_09_55](https://user-images.githubusercontent.com/105995521/209427236-ea8c0765-7d3f-439a-9e18-f87f40fee471.png)

Thank you ! :rocket:

**Comment by Theodlz** [comment]
Hi! So the lines you added in the pg_hba.conf should be added between the last local line, and the first host line, not on top of all the config as you did.

To make it easier during development, I suggest removing what you added and simply adding `host all all 127.0.0.1/32 trust` which will allow all connections.

Also, make sure that your postgresql is running! To do so, open a terminal and run `sudo systemctl status <name_of_your_postgresql_service>`

I guess the name will be `postgresql`, but it might be `postgresql-14`.

Keep me updated, and have a lovely christmas.

**Comment by jolyanem** [comment]
Hello @Theodlz ! 👋 I'm coming back for some updates. 
So, I checked if my `postgresql` was running and it is! 
Then, I moved the lines and add the line `host all all 127.0.0.1/32 trust` before all the host lines (and I make sure that everything was like at the beginning with no other changes). 
It looks like this now : 
<img width="476" alt="image" src="https://user-images.githubusercontent.com/105995521/209692622-0375088a-729d-4449-8982-c020e63bb08b.png">
but errors still remain on my `make log` when I try `make run`
<img width="268" alt="image" src="https://user-images.githubusercontent.com/105995521/209693477-1c063d10-0960-452d-9632-37d7206b9fa1.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/105995521/209694193-35c25d11-a4b2-4be7-87f9-3d117fa5ffd0.png">
And when I try `make db_clear && make db_init && make run` : 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/105995521/209693958-95c1470f-88f1-40a2-8cb5-0bfa69355b14.png">

**Comment by jolyanem** [comment]
Hi again ! Sorry, it finally worked ! I added the same line for iv6, (`host all all ::1/128 trust`) and now it displays Skyportal.
Now I just have to display the data as is empty for now but at least now I am connected to it! 

Thank you ! 🚀
