### ISSUE TITLE
Manon/Alix - Telescope search bar

### ISSUE THREAD

**Issue by AlixOlrc** [grandma-collaboration/skyportal_grandma_dev#43]
Hi !
With Manon, during the workshop, we worked on adding the telescope list as default display as well as a search bar for the telescopes.
We managed to display the list of telescopes but are still working on the search bar.

**Comment by aolrc-vinci** [comment]
Hi, I am having issues with loading Skyportal.
For some reasons, I am having the following error which leads to the localhost page to stay blank when charged.
Any idea what could be the problem ?

![image](https://user-images.githubusercontent.com/113455524/215091747-f29604be-e696-449c-bf79-0c1fae578c45.png)

**Comment by AlixOlrc** [comment]
Hi !
We're unable to progress because we are having problems with Skyportal.
I am unable to load skyportal, this is the error shown when i try to (resulting in a blank page for the localhost) : 

![image](https://user-images.githubusercontent.com/113455524/215093227-a3b839cb-441a-445c-b557-578fe6b844ae.png)

Any idea what could be the problem and how to solve it ?

**Comment by mcoughlin** [comment]
@aolrc-vinci Does this happen on a completely new git clone from the repository too?

**Comment by AlixOlrc** [comment]
Yes, I had another problem with skyportal before so I did  a new git clone and got this error.

**Comment by mcoughlin** [comment]
@aolrc-vinci What about in the inspect in your browser?

**Comment by AlixOlrc** [comment]
I got this and an 404 error (failed to load resource).

![image](https://user-images.githubusercontent.com/113455524/215097657-c7c1c6c2-82af-4fab-8371-9e05e463f4ec.png)

**Comment by mcoughlin** [comment]
@aolrc-vinci And there is nothing earlier explaining why the webpack would not build?

**Comment by AlixOlrc** [comment]
Nothing that I've seen no.
