### ISSUE TITLE
Manon Flament - Installing SkyPortal

### ISSUE THREAD

**Issue by ManonFlt** [grandma-collaboration/skyportal_grandma_dev#8]
Hello!
I am at the lauching part and the "make db_init" gives me the following error:

/bin/bash: python: command not found

Welcome to SkyPortal v (https://skyportal.io)

/usr/bin/env: ‘python’: No such file or directory
make[1]: *** [baselayer/Makefile:44: dependencies] Error 127
make: *** [Makefile:74: db_init] Error 2

**Comment by Theodlz** [comment]
@ManonFlt  if you are done with starting SkyPortal, please close this issue and move to the next step  which is described in issue https://github.com/grandma-collaboration/skyportal_grandma_dev/issues/12
