### ISSUE TITLE
Alix Olliéric - Installing SkyPortal

### ISSUE THREAD

**Issue by aolrc-vinci** [grandma-collaboration/skyportal_grandma_dev#9]
Hi !
I am currently in the process of setting up skyportal.
I am having issues with the `make run`  part and having the following errors :

> pip 20.0.2 is installed but pip==22.2.2 is required

and

> Traceback (most recent call last):
>   File "/home/alixo/skyportal/skyportal_env/bin/pip", line 5, in <module>
>     from pip._internal.cli.main import main
>   ....
>   File "/home/alixo/skyportal/skyportal_env/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
>     utils.deprecated(
> TypeError: deprecated() got an unexpected keyword argument 'name'
> make[1]: *** [baselayer/Makefile:45: dependencies] Error 1
> make: *** [Makefile:74: run] Error 2

**Comment by Theodlz** [comment]
Sounds good! Good luck

**Comment by Theodlz** [comment]
Hey @aolrc-vinci. Any updates?

**Comment by AlixOlrc** [comment]
Yes I realised I didn't clone the right fork and cloned the skyportal repository so I have to start the installation from the beginning on my fork. I should however be able to do start again relatively quickly since I've figured out most of my issues.

**Comment by Theodlz** [comment]
Awesome. Please tag me in a comment here ans close your issue once you're done.

**Comment by AlixOlrc** [comment]
Hi @Theodlz !
I'm having an issue with the `make db_init` and postgresql, I downloaded postgresql v14 but the one that is used in the db_init is the v12 and I can't find the pg_hba.conf file for this one.
The postgres client exited with the following error message:
> psql: error: fe_sendauth: no password supplied

I also tried to create a cluster using the v14 (of which I was able to edit the pg_hba file) but it's not allowing me to do so.

**Comment by Theodlz** [comment]
Hi @aolrc-vinci, please have a look at the `Installing PostgreSQL` from https://grandma-skyportal.readthedocs.io/dev_guide/
I wrote that documentation when I had the same problem. It should help :)

**Comment by AlixOlrc** [comment]
Hi @Theodlz  ! I come bearing good news !
I have finally succeeded at the installation.
Ready to start working now ! 🚀
